### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Derich367** [gabrielkim13/json-logic-cpp#6]
There is no license mentioned in this project.

Other json-logic implementations are licensed unter MIT (e.g. [json-logic-js](https://github.com/jwadhams/json-logic-js)).

Can you please add a license to this repository?

**Comment by tonuonu** [comment]
I just came to same point and wanted to open an issue :)

**Comment by gabrielkim13** [comment]
Done! Thanks for the suggestion!
